import { useEffect, useState } from "react";
import { ArrowRight, Brain, Database, FileMagnifyingGlass, LockKey, PaperPlaneTilt, ShareNetwork, Sparkle } from "@phosphor-icons/react";
import { isDirectQuestion } from "../lib/intent";

const liveStages = [
  { label: "Planner", detail: "Interpreting your question and assigning specialist work", icon: Brain },
  { label: "Data specialist", detail: "Checking the World Bank indicators in DuckDB", icon: Database },
  { label: "Document specialist", detail: "Retrieving relevant World Bank report evidence", icon: FileMagnifyingGlass },
  { label: "Synthesis agent", detail: "Combining the findings into a cited answer", icon: Sparkle },
];

export function AgentWorkspace({ action, inspectingVectorStore, localToolsAvailable, onClearConversation, onEnableLocal, onInspectVectorStore, onSubmit, prebuiltPrompts, question, reply, sending, setQuestion, suggestedQuestions, usingLocalData, vectorInspection }) {
  const stages = liveStages;
  const directReply = Boolean(reply?.limitations?.some((item) => /Direct conversation response|no data retrieval or model call/i.test(item)));
  const [stageIndex, setStageIndex] = useState(0);
  useEffect(() => {
    if (!sending) { setStageIndex(0); return undefined; }
    // Advance once through the handoff sequence and hold at synthesis. This is
    // a status timeline, not a looping animation that suggests repeat work.
    const timer = window.setInterval(() => setStageIndex((current) => Math.min(current + 1, stages.length - 1)), 1150);
    return () => window.clearInterval(timer);
  }, [sending, stages.length]);
  // A guided prompt only fills the composer. The user explicitly begins a run
  // with "Ask agent", preventing accidental model calls.
  function choosePrompt(prompt) { setQuestion(prompt); }

  return <article className="agent-workspace panel" aria-busy={sending}>
    <header className="agent-heading"><div><span className="eyebrow"><ShareNetwork size={15}/>Agent workspace</span><h2>Ask the development agent</h2><p>{usingLocalData ? "The coordinator delegates data and evidence checks, then returns one grounded answer. Follow-up questions retain this local conversation." : "Explore the public snapshot, or load the local workspace to ask the agent a live question."}</p></div><div className="agent-header-actions"><span className={`agent-mode ${usingLocalData ? "local" : "static"}`}><LockKey size={13}/>{usingLocalData ? "Live agent" : "Static demo"}</span>{usingLocalData && <button type="button" className="clear-memory" onClick={onClearConversation}>Clear follow-up memory</button>}</div></header>
    {!usingLocalData && localToolsAvailable && <div className="agent-enable"><div><strong>Use the local agent</strong><span>Loads the latest selected-country data into DuckDB. This does not call a model.</span></div><button type="button" onClick={onEnableLocal} disabled={Boolean(action)}>{action === "refresh" ? "Loading data…" : "Load local workspace"}<ArrowRight size={16}/></button></div>}
    <div className="agent-prompt-grid"><div className="agent-composer"><label htmlFor="chat-question">Your question</label><textarea id="chat-question" maxLength={500} value={question} onChange={(event) => setQuestion(event.target.value)} placeholder={usingLocalData ? "For example: Compare growth in the selected countries and identify evidence-backed differences." : "Choose a starter question, or load the local workspace to ask your own."}/><div className="chat-footer"><span>{usingLocalData ? "Live research routing" : "Static response"}</span><span>{question.length}/500</span><button type="button" onClick={() => onSubmit(question)} disabled={sending || !question.trim()}><PaperPlaneTilt size={16}/>{sending ? "Working…" : "Ask agent"}</button></div></div><div className="agent-starters"><span className="starter-label">Choose a guided question, then select Ask agent</span><div className="suggestion-list">{suggestedQuestions.map((item) => <button type="button" key={item} onClick={() => choosePrompt(item)} disabled={sending}>{item}<ArrowRight size={17}/></button>)}</div><div className="prompt-list">{prebuiltPrompts.map((item) => <button type="button" key={item.label} onClick={() => choosePrompt(item.prompt)} disabled={sending}>{item.label}</button>)}</div></div></div>
    {localToolsAvailable && usingLocalData && <section className="index-inspector"><div><strong>Document index</strong><p>Review the hosted file attachments and managed embedding status. This does not run a model.</p></div><button type="button" onClick={onInspectVectorStore} disabled={inspectingVectorStore}>{inspectingVectorStore ? "Inspecting…" : "Inspect document index"}</button>{vectorInspection && <div className="index-result"><span><strong>{vectorInspection.name}</strong> · {vectorInspection.usage_bytes ? `${Math.round(vectorInspection.usage_bytes / 1024)} KB indexed` : "No indexed content"}</span><p>{vectorInspection.embedding_visibility}</p><p>{vectorInspection.attached_files?.length || 0} attached file(s) · {vectorInspection.unattached_uploaded_files?.length || 0} uploaded file(s) still need attachment.</p>{vectorInspection.unattached_uploaded_files?.length > 0 && <ul>{vectorInspection.unattached_uploaded_files.slice(0, 5).map((file) => <li key={file.id}>{file.filename}</li>)}</ul>}</div>}</section>}
    {sending && !isDirectQuestion(question) && <section className="agent-progress" aria-live="polite"><div className="agent-progress-title"><span className="pulse-dot"/><strong>Agent team is working</strong><span>Live run</span></div><div className="agent-stage-list">{stages.map(({ label, detail, icon: Icon }, index) => <div className={`agent-stage ${index === stageIndex ? "active" : index < stageIndex ? "complete" : ""}`} key={label}><span className="stage-icon"><Icon size={17}/></span><span><strong>{label}</strong><small>{index === stageIndex ? `Working: ${detail}` : index < stageIndex ? "Completed and handed to the next specialist" : "Waiting for input from the previous specialist"}</small></span><i aria-hidden="true"/></div>)}</div></section>}
    <section className="agent-output" aria-live="polite"><div className="answer-label"><Sparkle size={16}/><strong>Agent answer</strong></div><textarea readOnly aria-label="Agent answer text" value={sending ? "The agent team is researching your question…" : reply?.answer || "Your completed answer will appear here."}/>{reply && <div className="answer-meta"><span>{reply.citation || reply.citations?.map((item) => item.title).join(" · ") || (directReply ? "Direct response · no research run" : reply.model ? "Live managed-RAG response" : "Static demonstration")}</span>{reply.handoffs?.length > 0 && <span>Route: {reply.handoffs.map((step) => step.to_agent).join(" → ")}</span>}</div>}</section>
    {reply && !directReply && <section className="research-summary" aria-label="Research summary"><div><span className="eyebrow">Completed research</span><h3>Research summary</h3></div><dl><div><dt>Outcome</dt><dd>Answer and evidence prepared</dd></div><div><dt>Evidence</dt><dd>{reply.citations?.length ? `${reply.citations.length} cited source${reply.citations.length === 1 ? "" : "s"}` : "Structured data checks"}</dd></div><div><dt>Workflow</dt><dd>{reply.handoffs?.length ? `${reply.handoffs.length} specialist handoffs` : "Direct evidence summary"}</dd></div></dl></section>}
  </article>;
}
